export const LEAD_PIPELINE = [
  "NEW",
  "CONTACTED",
  "INTERESTED",
  "SITE_VISIT_SCHEDULED",
  "SITE_VISIT_DONE",
  "NEGOTIATION",
  "BOOKING_TOKEN",
  "BOOKED",
  "AGREEMENT",
  "REGISTERED",
  "POSSESSION",
] as const;

export const LEAD_STATUS_LABELS: Record<string, string> = {
  NEW: "New",
  CONTACTED: "Contacted",
  INTERESTED: "Interested",
  SITE_VISIT_SCHEDULED: "Site Visit Scheduled",
  SITE_VISIT_DONE: "Site Visit Done",
  NEGOTIATION: "Negotiation",
  BOOKING_TOKEN: "Booking Token",
  BOOKED: "Booked",
  AGREEMENT: "Agreement",
  REGISTERED: "Registered",
  POSSESSION: "Possession",
  LOST: "Lost",
};

export const LEAD_STATUS_BADGE: Record<string, "default" | "secondary" | "success" | "warning" | "destructive" | "muted" | "outline"> = {
  NEW: "secondary",
  CONTACTED: "outline",
  INTERESTED: "default",
  SITE_VISIT_SCHEDULED: "warning",
  SITE_VISIT_DONE: "warning",
  NEGOTIATION: "warning",
  BOOKING_TOKEN: "success",
  BOOKED: "success",
  AGREEMENT: "success",
  REGISTERED: "success",
  POSSESSION: "success",
  LOST: "destructive",
};

export const LEAD_SOURCE_LABELS: Record<string, string> = {
  WEBSITE_FORM: "Website Form",
  WEBHOOK: "Webhook",
  API: "API",
  JAVASCRIPT_FORM: "JavaScript Form",
  WORDPRESS_PLUGIN: "WordPress Plugin",
  META_LEAD_ADS: "Meta Lead Ads",
  META_CAPI: "Meta CAPI",
  GOOGLE_LEAD_FORM: "Google Lead Form",
  GOOGLE_LANDING_PAGE: "Google Landing Page",
  GOOGLE_OFFLINE_CONVERSION: "Google Offline Conversion",
  WHATSAPP_CLICK_TO_CHAT: "Click to WhatsApp",
  WHATSAPP_CHATBOT: "WhatsApp Chatbot",
  WHATSAPP_MANUAL: "WhatsApp (Manual)",
  MAGICBRICKS: "MagicBricks",
  ACRES99: "99acres",
  HOUSING_COM: "Housing.com",
  NOBROKER: "NoBroker",
  INDIAPROPERTY: "IndiaProperty",
  SQUAREYARDS: "Square Yards",
  CHANNEL_PARTNER: "Channel Partner",
  WALK_IN: "Walk-in",
  REFERRAL: "Referral",
  CSV_IMPORT: "CSV Import",
  EXCEL_IMPORT: "Excel Import",
  OTHER: "Other",
};

export const ACTIVITY_TYPE_LABELS: Record<string, string> = {
  CALL: "Call",
  WHATSAPP: "WhatsApp",
  EMAIL: "Email",
  SMS: "SMS",
  NOTE: "Note",
  TASK: "Task",
  MEETING: "Meeting",
  STATUS_CHANGE: "Status Change",
  SITE_VISIT: "Site Visit",
  ASSIGNMENT: "Assignment",
  SYSTEM: "System",
};

export const LOST_REASONS = [
  "Budget mismatch",
  "Bought elsewhere",
  "Not interested",
  "Unresponsive",
  "Location mismatch",
  "Timeline mismatch",
  "Other",
];
